'\" t
.\"     Title: cjconf-add-default
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/03/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CJCONF\-ADD\-DEFAULT" "1" "03/03/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cjconf-add-default \- Merge default peers into default config\&.
.SH "SYNOPSIS"
.sp
\fBcjconf\-add\-default\fR
.SH "DESCRIPTION"
.sp
cjconf\-add\-default(1) merges a set of default peers stored in /etc/cjdroute\&.conf\&.default, into your primary config at /etc/cjdroute\&.conf\&. It takes no arguments, and is very simple\&. You can view its source code as an example of how to merge configs in other locations\&.
.SH "EXAMPLES"
.PP
\fBcjconf\-add\-default\fR
.RS 4
Merge peers at /etc/cjdroute\&.conf\&.default into /etc/cjdroute\&.conf\&.
.RE
.SH "BUGS"
.sp
See https://github\&.com/campadrenalin/cjdns\-deb/issues
.SH "AUTHOR"
.sp
cjconf\-add\-default was written by Philip Horger in 2012\&. cjdroute was written by Caleb Delisle\&.
.SH "RESOURCES"
.sp
Github: https://github\&.com/campadrenalin/cjdns\-deb/
.SH "COPYING"
.sp
Copyright (C) 2012 Philip Horger\&. Free use of this software is granted under the terms of the GNU General Public License (GPL)\&.
