'\" t
.\"     Title: cjdinfo
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/03/2012
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CJDINFO" "1" "03/03/2012" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cjdinfo \- Information about your cjdroute setup and instance\&.
.SH "SYNOPSIS"
.sp
\fBcjdinfo\fR [commands|tunnel|address|key]
.SH "DESCRIPTION"
.sp
The cjdinfo(1) command is useful for finding out the key details of your cjdroute instance and setup\&. It was born out of a need to move functionality out of cjdroute for simplicity, and have a place to add informative more informative subcommands as the author saw fit\&.
.SH "SUBCOMMANDS"
.PP
\fBcommands\fR
.RS 4
The commands that need to be run to connect the tunnel device to the network interface, and allow cjdroute to provide that service\&. Used by (and formerly, in) cjdrouted\&.
.RE
.PP
\fBtunnel\fR
.RS 4
Create a tunnel if no appropriately configured one exists, and return its name\&. Useful in scripts\&. Also a cjdrouted refugee\&.
.RE
.PP
\fBaddress\fR
.RS 4
The IPv6 address of your cjdroute instance\&. Currently it requires you to be running, or have run, cjdroute through cjdrouted\&. That\(cqs because it determines your address based on the logs\&. However, at some point in the future this will be changed to be based on the result of "cjdinfo commands"\&.
.RE
.PP
\fBkey\fR
.RS 4
The public key of your cjdroute instance\&. Like the address subcommand, it is log\-based, and requires log information in /var/log/cjdns/cjdrouted\&.current\&.log\&. Unlike the address subcommand, this is impossible to fix\&.
.RE
.SH "BUGS"
.sp
See https://github\&.com/campadrenalin/cjdns\-deb/issues
.SH "AUTHOR"
.sp
cjdinfo was written by Philip Horger in 2012\&. cjdroute was written by Caleb Delisle\&.
.SH "RESOURCES"
.sp
Github: https://github\&.com/campadrenalin/cjdns\-deb/
.SH "COPYING"
.sp
Copyright (C) 2012 Philip Horger\&. Free use of this software is granted under the terms of the GNU General Public License (GPL)\&.
